lunchapp/config/routes.rb
Rails.application.routes.draw do
  root 'lunches#index'
  resources :lunches
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

lunchapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

lunchapp/app/models/lunch.rb
class Lunch < ApplicationRecord
  belongs_to :user

  validates_presence_of %i(name cost_rands cost_cents enjoyment prep_time_minutes user_id)
end

lunchapp/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

lunchapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

lunchapp/app/controllers/lunches_controller.rb
class LunchesController < ApplicationController
  before_action :set_lunch, only: [:show, :edit, :update, :destroy]

  def index
    @lunches = Lunch.all
  end

  def show
  end

  def new
    @lunch = Lunch.new
  end

  def edit
  end

  def create
    @lunch = Lunch.new(lunch_params.merge(user: current_user))

    respond_to do |format|
      if @lunch.save
        format.html { redirect_to @lunch, notice: 'Lunch was successfully created.' }
        format.json { render :show, status: :created, location: @lunch }
      else
        format.html { render :new }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @lunch.update(lunch_params)
        format.html { redirect_to @lunch, notice: 'Lunch was successfully updated.' }
        format.json { render :show, status: :ok, location: @lunch }
      else
        format.html { render :edit }
        format.json { render json: @lunch.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lunch.destroy
    respond_to do |format|
      format.html { redirect_to lunches_url, notice: 'Lunch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_lunch
      @lunch = Lunch.find(params[:id])
    end

    def lunch_params
      params.require(:lunch).permit(:name, :cost_rands, :cost_cents, :enjoyment, :prep_time_minutes)
    end
end

lunchapp/app/helpers/application_helper.rb
module ApplicationHelper
end

lunchapp/app/helpers/lunches_helper.rb
module LunchesHelper
end

lunchapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LunchScoreboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

lunchapp/app/views/lunches/_form.html.slim
= form_for @lunch do |f|
  - if @lunch.errors.any?
    #error_explanation
      h2 = "#{pluralize(@lunch.errors.count, "error")} prohibited this lunch from being saved:"
      ul
        - @lunch.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :cost_rands
    = f.number_field :cost_rands
  .field
    = f.label :cost_cents
    = f.number_field :cost_cents
  .field
    = f.label :enjoyment
    = f.number_field :enjoyment
  .field
    = f.label :prep_time_minutes
    = f.number_field :prep_time_minutes
  .actions = f.submit

lunchapp/app/views/lunches/edit.html.slim
h1 Editing lunch

== render 'form'

=> link_to 'Show', @lunch
'|
=< link_to 'Back', lunches_path

lunchapp/app/views/lunches/index.html.slim
h1 Listing lunches

table.table.table-bordered
  thead
    tr
      th Name
      th Cost
      th Enjoyment
      th Prep time minutes
      th User
      th
      th
      th

  tbody
    - @lunches.each do |lunch|
      tr
        td = lunch.name
        td = "R#{lunch.cost_rands}.#{lunch.cost_cents}"
        td = lunch.enjoyment
        td = lunch.prep_time_minutes
        td = lunch.user.email
        td = link_to 'Show', lunch
        td = link_to 'Edit', edit_lunch_path(lunch)
        td = link_to 'Destroy', lunch, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Lunch', new_lunch_path, class: 'btn btn-info'

lunchapp/app/views/lunches/new.html.slim
h1 New lunch

== render 'form'

= link_to 'Back', lunches_path

lunchapp/app/views/lunches/show.html.slim
p#notice = notice

p
  strong Name:
  = @lunch.name
p
  strong Cost:
  = "R#{@lunch.cost_rands}.#{@lunch.cost_cents}"
p
  strong Enjoyment:
  = @lunch.enjoyment
p
  strong Prep time minutes:
  = @lunch.prep_time_minutes
p
  strong User:
  = @lunch.user.email

=> link_to 'Edit', edit_lunch_path(@lunch)
'|
=< link_to 'Back', lunches_path